services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    image: jekyll:latest
    container_name: jekyll
    ports:
      - "4000:4000"
    volumes:
      - ./docs:/dp.docs/docs
