# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hidale.com Docs
tagline: Documentation and help for Hidale services and software
description: >-
  Hidale.com documentation for software and services like dp.kinect,
  dp.kinect2, dp.kinect3, and dp.oak; used for computer vision, interaction,
  multimedia art, and participatory experiences
baseurl: "/dp.docs"                 # the subpath of your site, e.g. /blog
url: "https://docs.hidale.com"      # protocol and base hostname for your site, e.g. http://example.com
domain: docs.hidale.com             # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#email: your-email@example.com
#twitter_username: jekyllrb
#github_username:  diablodale
github_repo: diablodale/dp.docs
social:
  name: Dale Phurrough
  links:
    - https://github.com/diablodale

# local testing
host: 0.0.0.0
#port: 80 # defaults to 4000
#livereload: true # Reload a page automatically on the browser when its content is edited.

# Build settings
theme: just-the-docs
ignore_theme_config: true  # important to use defaults of JTD's code and not JTD's _config.yml
page_excerpts: true
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-relative-links
  - jekyll-link-attributes
  - jekyll-redirect-from
mermaid:
  version: "10.9" # pick from https://cdn.jsdelivr.net/npm/mermaid/
  config: # mermaid.initialize(config)
    startOnLoad: false # required otherwise mermaid run() runs twice

permalink: pretty
relative_links:
  collections: true
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _top
  exclude:
    - https://hidale.com(?:/.*)?

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md

#header_pages:
#  - dp.kinect-tags-cats.md
#  - dp.kinect2-tags-cats.md
#  - dp.kinect3-tags-cats.md
#  - dp.oak-tags-cats.md
#  - about.markdown

collections:
  max:
    output: true
    permalink: /:collection/:slugified_categories/:name

  hardware:
    output: true
    permalink: /:collection/:slugified_categories/:name

defaults:
  - scope:
      path: "_max/attributes/"
      type: max
    values:
      layout: attribute
      categories: attributes
      parent: Attributes
  - scope:
      path: "_max/methods/"
      type: max
    values:
      layout: method
      categories: methods
      parent: Methods
  - scope:
      path: "_max/tutorials/"
      type: max
    values:
      layout: tutorial
      categories: tutorials
      parent: Tutorials
  - scope:
      path: "_hardware/sensors/"
      type: hardware
    values:
      layout: hardware
      categories: sensors
      parent: Sensors

# Just the Docs configuration ###################################################
search_enabled: true
search:
  heading_level: 3 # default is 2
  tokenizer_separator: /[\s\-/_]+/

heading_anchors: true
heading_anchors_autoid: true
nav_sort: case_insensitive
nav_external_links:
  - title: Download, trial, license
    url: https://hidale.com
    hide_icon: true

footer_content: "&copy; Dale Phurrough"
#ga_tracking:
#ga_tracking_anonymize_ip: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/diablodale/dp.docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

color_scheme: dark
#callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: all

just_the_docs:
  collections:
    max:
      name: Max plugins
      # Exclude the collection from the navigation, default=false
      # nav_exclude: true
      # Fold the collection in the navigation, default=false
      # nav_fold: true
      # Exclude the collection from the search, default=false
      # search_exclude: true
    hardware:
      name: Hardware information
