# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hidale Software Docs
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Interactive multimedia art, software engineering, and participatory experiences
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.hidale.com" # the base hostname & protocol for your site, e.g. http://example.com
domain: docs.hidale.com        # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#twitter_username: jekyllrb
#github_username:  diablodale
github_repo: diablodale/dp.docs

# local testing
host: 0.0.0.0
#port: 80 # defaults to 4000
#livereload: true # Reload a page automatically on the browser when its content is edited.

# Build settings
theme: minima
page_excerpts: true
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

#header_pages:
#  - dp.kinect-tags-cats.md
#  - dp.kinect2-tags-cats.md
#  - dp.kinect3-tags-cats.md
#  - dp.oak-tags-cats.md
#  - about.markdown

collections:
  maxplugins:
    output: true

defaults:
  - scope:
      path: "*/attributes"
      type: maxplugins
    values:
      layout: attribute
